print >> sys.stderr, "Start analyze samples"

iSample = -1

for sample in samples:
  iSample = iSample + 1
  print >> sys.stderr, "   Sample #", iSample
  filenames = sample[5:]
  for filename in filenames:
    print >> sys.stderr, "      Open file:", filename
    tfile = ROOT.TFile(filename)
    
    treeName = "muAlAnalyzer/Info"
    print >> sys.stderr, "      Read tree", treeName
    Info = tfile.Get(treeName)
    for info in Info:
      fillGenMuons    = info.fillGenMuons
      fillRecoMuons   = info.fillRecoMuons
      fillRecoDimuons = info.fillRecoDimuons
    
    if ( fillGenMuons ): print >> sys.stderr,    "         fillGenMuons = ",    fillGenMuons
    if ( fillRecoMuons ): print >> sys.stderr,   "         fillRecoMuons = ",   fillRecoMuons
    if ( fillRecoDimuons ): print >> sys.stderr, "         fillRecoDimuons = ", fillRecoDimuons
    
    if ( fillRecoMuons ):
      counterRecoMuons = 0 # reset counter for every file
      treeName = "muAlAnalyzer/recoMuons"
      print >> sys.stderr, "      Read tree", treeName
      recoMuons = tfile.Get(treeName)
      print >> sys.stderr, "         Total number of entries in the tree:", recoMuons.GetEntriesFast()
      
      for mu in recoMuons:
        if maxEntries > 0 and counterRecoMuons >= maxEntries:
          break
        if ( not counterRecoMuons%100000 ):
          print >> sys.stderr, counterRecoMuons
        counterRecoMuons = counterRecoMuons + 1
        if ( mu.glb ):
          h_glb_pt[iSample].Fill(mu.glb_pt)
          h_glb_nchi2[iSample].Fill(mu.glb_nchi2)
          h_glb_eta[iSample].Fill(mu.glb_eta)
          h_glb_phi[iSample].Fill(mu.glb_phi)
          
          h_glb_trk_pt[iSample].Fill(mu.glb_trk_pt)
#          h_glb_trk_nchi2[iSample].Fill(mu.glb_trk_nchi2)
          h_glb_trk_eta[iSample].Fill(mu.glb_trk_eta)
          h_glb_trk_phi[iSample].Fill(mu.glb_trk_phi)
          
          if ( mu.glb_pic ):
            h_glb_pic_pt[iSample].Fill(mu.glb_pic_pt)
#            h_glb_pic_nchi2[iSample].Fill(mu.glb_pic_nchi2)
            h_glb_pic_eta[iSample].Fill(mu.glb_pic_eta)
            h_glb_pic_phi[iSample].Fill(mu.glb_pic_phi)
          
        if ( mu.sta ):
          h_sta_pt[iSample].Fill(mu.sta_pt)
          h_sta_nchi2[iSample].Fill(mu.sta_nchi2)
          h_sta_eta[iSample].Fill(mu.sta_eta)
          h_sta_phi[iSample].Fill(mu.sta_phi)
        
        if ( mu.sta and mu.glb and mu.glb_pt > 30):
          if ( mu.sta_pt != 0.0 and mu.glb_pt != 0.0 ):
            ptRes_sta_glb = mu.q/mu.sta_pt - mu.q/mu.glb_pt
            h_ptRes_sta_glb[iSample].Fill(ptRes_sta_glb)
            # resolution vs eta
            if ( mu.glb_eta >= -2.4 and mu.glb_eta <= -2.1 ): h_ptRes_sta_glb_eta_m24_m21[iSample].Fill(ptRes_sta_glb)
            if ( mu.glb_eta >= -2.1 and mu.glb_eta <= -1.8 ): h_ptRes_sta_glb_eta_m21_m18[iSample].Fill(ptRes_sta_glb)
            if ( mu.glb_eta >= -1.8 and mu.glb_eta <= -1.5 ): h_ptRes_sta_glb_eta_m18_m15[iSample].Fill(ptRes_sta_glb)
            if ( mu.glb_eta >= -1.5 and mu.glb_eta <= -1.2 ): h_ptRes_sta_glb_eta_m15_m12[iSample].Fill(ptRes_sta_glb)
            if ( mu.glb_eta >= -1.2 and mu.glb_eta <= -0.9 ): h_ptRes_sta_glb_eta_m12_m09[iSample].Fill(ptRes_sta_glb)
            if ( mu.glb_eta >= -0.9 and mu.glb_eta <= -0.6 ): h_ptRes_sta_glb_eta_m09_m06[iSample].Fill(ptRes_sta_glb)
            if ( mu.glb_eta >= -0.6 and mu.glb_eta <= -0.3 ): h_ptRes_sta_glb_eta_m06_m03[iSample].Fill(ptRes_sta_glb)
            if ( mu.glb_eta >= -0.3 and mu.glb_eta <=  0.0 ): h_ptRes_sta_glb_eta_m03_m00[iSample].Fill(ptRes_sta_glb)
            if ( mu.glb_eta >=  0.0 and mu.glb_eta <=  0.3 ): h_ptRes_sta_glb_eta_p00_p03[iSample].Fill(ptRes_sta_glb)
            if ( mu.glb_eta >=  0.3 and mu.glb_eta <=  0.6 ): h_ptRes_sta_glb_eta_p03_p06[iSample].Fill(ptRes_sta_glb)
            if ( mu.glb_eta >=  0.6 and mu.glb_eta <=  0.9 ): h_ptRes_sta_glb_eta_p06_p09[iSample].Fill(ptRes_sta_glb)
            if ( mu.glb_eta >=  0.9 and mu.glb_eta <=  1.2 ): h_ptRes_sta_glb_eta_p09_p12[iSample].Fill(ptRes_sta_glb)
            if ( mu.glb_eta >=  1.2 and mu.glb_eta <=  1.5 ): h_ptRes_sta_glb_eta_p12_p15[iSample].Fill(ptRes_sta_glb)
            if ( mu.glb_eta >=  1.5 and mu.glb_eta <=  1.8 ): h_ptRes_sta_glb_eta_p15_p18[iSample].Fill(ptRes_sta_glb)
            if ( mu.glb_eta >=  1.8 and mu.glb_eta <=  2.1 ): h_ptRes_sta_glb_eta_p18_p21[iSample].Fill(ptRes_sta_glb)
            if ( mu.glb_eta >=  2.1 and mu.glb_eta <=  2.4 ): h_ptRes_sta_glb_eta_p21_p24[iSample].Fill(ptRes_sta_glb)
            # resolution vs phi
            if ( mu.glb_phi >= -3.2 and mu.glb_phi <= -2.8 ): h_ptRes_sta_glb_phi_m32_m28[iSample].Fill(ptRes_sta_glb)
            if ( mu.glb_phi >= -2.8 and mu.glb_phi <= -2.4 ): h_ptRes_sta_glb_phi_m28_m24[iSample].Fill(ptRes_sta_glb)
            if ( mu.glb_phi >= -2.4 and mu.glb_phi <= -2.0 ): h_ptRes_sta_glb_phi_m24_m20[iSample].Fill(ptRes_sta_glb)
            if ( mu.glb_phi >= -2.0 and mu.glb_phi <= -1.6 ): h_ptRes_sta_glb_phi_m20_m16[iSample].Fill(ptRes_sta_glb)
            if ( mu.glb_phi >= -1.6 and mu.glb_phi <= -1.2 ): h_ptRes_sta_glb_phi_m16_m12[iSample].Fill(ptRes_sta_glb)
            if ( mu.glb_phi >= -1.2 and mu.glb_phi <= -0.8 ): h_ptRes_sta_glb_phi_m12_m08[iSample].Fill(ptRes_sta_glb)
            if ( mu.glb_phi >= -0.8 and mu.glb_phi <= -0.4 ): h_ptRes_sta_glb_phi_m08_m04[iSample].Fill(ptRes_sta_glb)
            if ( mu.glb_phi >= -0.4 and mu.glb_phi <=  0.0 ): h_ptRes_sta_glb_phi_m04_m00[iSample].Fill(ptRes_sta_glb)
            if ( mu.glb_phi >=  0.0 and mu.glb_phi <=  0.4 ): h_ptRes_sta_glb_phi_p00_p04[iSample].Fill(ptRes_sta_glb)
            if ( mu.glb_phi >=  0.4 and mu.glb_phi <=  0.8 ): h_ptRes_sta_glb_phi_p04_p08[iSample].Fill(ptRes_sta_glb)
            if ( mu.glb_phi >=  0.8 and mu.glb_phi <=  1.2 ): h_ptRes_sta_glb_phi_p08_p12[iSample].Fill(ptRes_sta_glb)
            if ( mu.glb_phi >=  1.2 and mu.glb_phi <=  1.6 ): h_ptRes_sta_glb_phi_p12_p16[iSample].Fill(ptRes_sta_glb)
            if ( mu.glb_phi >=  1.6 and mu.glb_phi <=  2.0 ): h_ptRes_sta_glb_phi_p16_p20[iSample].Fill(ptRes_sta_glb)
            if ( mu.glb_phi >=  2.0 and mu.glb_phi <=  2.4 ): h_ptRes_sta_glb_phi_p20_p24[iSample].Fill(ptRes_sta_glb)
            if ( mu.glb_phi >=  2.4 and mu.glb_phi <=  2.8 ): h_ptRes_sta_glb_phi_p24_p28[iSample].Fill(ptRes_sta_glb)
            if ( mu.glb_phi >=  2.8 and mu.glb_phi <=  3.2 ): h_ptRes_sta_glb_phi_p28_p32[iSample].Fill(ptRes_sta_glb)
            if ( mu.glb_eta >=  -0.9 and mu.glb_eta <=  0.9 ): 
              if ( mu.glb_phi >= -3.2 and mu.glb_phi <= -2.8 ): h_ptRes_sta_glbB_phi_m32_m28[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >= -2.8 and mu.glb_phi <= -2.4 ): h_ptRes_sta_glbB_phi_m28_m24[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >= -2.4 and mu.glb_phi <= -2.0 ): h_ptRes_sta_glbB_phi_m24_m20[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >= -2.0 and mu.glb_phi <= -1.6 ): h_ptRes_sta_glbB_phi_m20_m16[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >= -1.6 and mu.glb_phi <= -1.2 ): h_ptRes_sta_glbB_phi_m16_m12[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >= -1.2 and mu.glb_phi <= -0.8 ): h_ptRes_sta_glbB_phi_m12_m08[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >= -0.8 and mu.glb_phi <= -0.4 ): h_ptRes_sta_glbB_phi_m08_m04[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >= -0.4 and mu.glb_phi <=  0.0 ): h_ptRes_sta_glbB_phi_m04_m00[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >=  0.0 and mu.glb_phi <=  0.4 ): h_ptRes_sta_glbB_phi_p00_p04[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >=  0.4 and mu.glb_phi <=  0.8 ): h_ptRes_sta_glbB_phi_p04_p08[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >=  0.8 and mu.glb_phi <=  1.2 ): h_ptRes_sta_glbB_phi_p08_p12[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >=  1.2 and mu.glb_phi <=  1.6 ): h_ptRes_sta_glbB_phi_p12_p16[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >=  1.6 and mu.glb_phi <=  2.0 ): h_ptRes_sta_glbB_phi_p16_p20[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >=  2.0 and mu.glb_phi <=  2.4 ): h_ptRes_sta_glbB_phi_p20_p24[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >=  2.4 and mu.glb_phi <=  2.8 ): h_ptRes_sta_glbB_phi_p24_p28[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >=  2.8 and mu.glb_phi <=  3.2 ): h_ptRes_sta_glbB_phi_p28_p32[iSample].Fill(ptRes_sta_glb)
            if ( mu.glb_eta >=  0.9 and mu.glb_eta <=  2.4 ): 
              if ( mu.glb_phi >= -3.2 and mu.glb_phi <= -2.8 ): h_ptRes_sta_glbEOp_phi_m32_m28[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >= -2.8 and mu.glb_phi <= -2.4 ): h_ptRes_sta_glbEOp_phi_m28_m24[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >= -2.4 and mu.glb_phi <= -2.0 ): h_ptRes_sta_glbEOp_phi_m24_m20[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >= -2.0 and mu.glb_phi <= -1.6 ): h_ptRes_sta_glbEOp_phi_m20_m16[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >= -1.6 and mu.glb_phi <= -1.2 ): h_ptRes_sta_glbEOp_phi_m16_m12[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >= -1.2 and mu.glb_phi <= -0.8 ): h_ptRes_sta_glbEOp_phi_m12_m08[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >= -0.8 and mu.glb_phi <= -0.4 ): h_ptRes_sta_glbEOp_phi_m08_m04[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >= -0.4 and mu.glb_phi <=  0.0 ): h_ptRes_sta_glbEOp_phi_m04_m00[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >=  0.0 and mu.glb_phi <=  0.4 ): h_ptRes_sta_glbEOp_phi_p00_p04[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >=  0.4 and mu.glb_phi <=  0.8 ): h_ptRes_sta_glbEOp_phi_p04_p08[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >=  0.8 and mu.glb_phi <=  1.2 ): h_ptRes_sta_glbEOp_phi_p08_p12[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >=  1.2 and mu.glb_phi <=  1.6 ): h_ptRes_sta_glbEOp_phi_p12_p16[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >=  1.6 and mu.glb_phi <=  2.0 ): h_ptRes_sta_glbEOp_phi_p16_p20[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >=  2.0 and mu.glb_phi <=  2.4 ): h_ptRes_sta_glbEOp_phi_p20_p24[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >=  2.4 and mu.glb_phi <=  2.8 ): h_ptRes_sta_glbEOp_phi_p24_p28[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >=  2.8 and mu.glb_phi <=  3.2 ): h_ptRes_sta_glbEOp_phi_p28_p32[iSample].Fill(ptRes_sta_glb)
            if ( mu.glb_eta >=  -2.4 and mu.glb_eta <=  -0.9 ): 
              if ( mu.glb_phi >= -3.2 and mu.glb_phi <= -2.8 ): h_ptRes_sta_glbEOm_phi_m32_m28[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >= -2.8 and mu.glb_phi <= -2.4 ): h_ptRes_sta_glbEOm_phi_m28_m24[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >= -2.4 and mu.glb_phi <= -2.0 ): h_ptRes_sta_glbEOm_phi_m24_m20[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >= -2.0 and mu.glb_phi <= -1.6 ): h_ptRes_sta_glbEOm_phi_m20_m16[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >= -1.6 and mu.glb_phi <= -1.2 ): h_ptRes_sta_glbEOm_phi_m16_m12[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >= -1.2 and mu.glb_phi <= -0.8 ): h_ptRes_sta_glbEOm_phi_m12_m08[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >= -0.8 and mu.glb_phi <= -0.4 ): h_ptRes_sta_glbEOm_phi_m08_m04[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >= -0.4 and mu.glb_phi <=  0.0 ): h_ptRes_sta_glbEOm_phi_m04_m00[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >=  0.0 and mu.glb_phi <=  0.4 ): h_ptRes_sta_glbEOm_phi_p00_p04[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >=  0.4 and mu.glb_phi <=  0.8 ): h_ptRes_sta_glbEOm_phi_p04_p08[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >=  0.8 and mu.glb_phi <=  1.2 ): h_ptRes_sta_glbEOm_phi_p08_p12[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >=  1.2 and mu.glb_phi <=  1.6 ): h_ptRes_sta_glbEOm_phi_p12_p16[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >=  1.6 and mu.glb_phi <=  2.0 ): h_ptRes_sta_glbEOm_phi_p16_p20[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >=  2.0 and mu.glb_phi <=  2.4 ): h_ptRes_sta_glbEOm_phi_p20_p24[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >=  2.4 and mu.glb_phi <=  2.8 ): h_ptRes_sta_glbEOm_phi_p24_p28[iSample].Fill(ptRes_sta_glb)
              if ( mu.glb_phi >=  2.8 and mu.glb_phi <=  3.2 ): h_ptRes_sta_glbEOm_phi_p28_p32[iSample].Fill(ptRes_sta_glb)
        ''' 
        if ( mu.sta and mu.glb and mu.glb_gen_pt > 30):
          if ( mu.sta_pt != 0.0 and mu.glb_gen_pt != 0.0 ):
            ptRes_sta_glb_gen = mu.q/mu.sta_pt - mu.q/mu.glb_gen_pt
            h_ptRes_sta_glb_gen[iSample].Fill(ptRes_sta_glb_gen)
            # resolution vs eta
            if ( mu.glb_gen_eta >= -2.4 and mu.glb_gen_eta <= -2.1 ): h_ptRes_sta_glb_gen_eta_m24_m21[iSample].Fill(ptRes_sta_glb_gen)
            if ( mu.glb_gen_eta >= -2.1 and mu.glb_gen_eta <= -1.8 ): h_ptRes_sta_glb_gen_eta_m21_m18[iSample].Fill(ptRes_sta_glb_gen)
            if ( mu.glb_gen_eta >= -1.8 and mu.glb_gen_eta <= -1.5 ): h_ptRes_sta_glb_gen_eta_m18_m15[iSample].Fill(ptRes_sta_glb_gen)
            if ( mu.glb_gen_eta >= -1.5 and mu.glb_gen_eta <= -1.2 ): h_ptRes_sta_glb_gen_eta_m15_m12[iSample].Fill(ptRes_sta_glb_gen)
            if ( mu.glb_gen_eta >= -1.2 and mu.glb_gen_eta <= -0.9 ): h_ptRes_sta_glb_gen_eta_m12_m09[iSample].Fill(ptRes_sta_glb_gen)
            if ( mu.glb_gen_eta >= -0.9 and mu.glb_gen_eta <= -0.6 ): h_ptRes_sta_glb_gen_eta_m09_m06[iSample].Fill(ptRes_sta_glb_gen)
            if ( mu.glb_gen_eta >= -0.6 and mu.glb_gen_eta <= -0.3 ): h_ptRes_sta_glb_gen_eta_m06_m03[iSample].Fill(ptRes_sta_glb_gen)
            if ( mu.glb_gen_eta >= -0.3 and mu.glb_gen_eta <=  0.0 ): h_ptRes_sta_glb_gen_eta_m03_m00[iSample].Fill(ptRes_sta_glb_gen)
            if ( mu.glb_gen_eta >=  0.0 and mu.glb_gen_eta <=  0.3 ): h_ptRes_sta_glb_gen_eta_p00_p03[iSample].Fill(ptRes_sta_glb_gen)
            if ( mu.glb_gen_eta >=  0.3 and mu.glb_gen_eta <=  0.6 ): h_ptRes_sta_glb_gen_eta_p03_p06[iSample].Fill(ptRes_sta_glb_gen)
            if ( mu.glb_gen_eta >=  0.6 and mu.glb_gen_eta <=  0.9 ): h_ptRes_sta_glb_gen_eta_p06_p09[iSample].Fill(ptRes_sta_glb_gen)
            if ( mu.glb_gen_eta >=  0.9 and mu.glb_gen_eta <=  1.2 ): h_ptRes_sta_glb_gen_eta_p09_p12[iSample].Fill(ptRes_sta_glb_gen)
            if ( mu.glb_gen_eta >=  1.2 and mu.glb_gen_eta <=  1.5 ): h_ptRes_sta_glb_gen_eta_p12_p15[iSample].Fill(ptRes_sta_glb_gen)
            if ( mu.glb_gen_eta >=  1.5 and mu.glb_gen_eta <=  1.8 ): h_ptRes_sta_glb_gen_eta_p15_p18[iSample].Fill(ptRes_sta_glb_gen)
            if ( mu.glb_gen_eta >=  1.8 and mu.glb_gen_eta <=  2.1 ): h_ptRes_sta_glb_gen_eta_p18_p21[iSample].Fill(ptRes_sta_glb_gen)
            if ( mu.glb_gen_eta >=  2.1 and mu.glb_gen_eta <=  2.4 ): h_ptRes_sta_glb_gen_eta_p21_p24[iSample].Fill(ptRes_sta_glb_gen)
            # resolution vs phi
            if ( mu.glb_gen_phi >= -3.2 and mu.glb_gen_phi <= -2.8 ): h_ptRes_sta_glb_gen_phi_m32_m28[iSample].Fill(ptRes_sta_glb_gen)
            if ( mu.glb_gen_phi >= -2.8 and mu.glb_gen_phi <= -2.4 ): h_ptRes_sta_glb_gen_phi_m28_m24[iSample].Fill(ptRes_sta_glb_gen)
            if ( mu.glb_gen_phi >= -2.4 and mu.glb_gen_phi <= -2.0 ): h_ptRes_sta_glb_gen_phi_m24_m20[iSample].Fill(ptRes_sta_glb_gen)
            if ( mu.glb_gen_phi >= -2.0 and mu.glb_gen_phi <= -1.6 ): h_ptRes_sta_glb_gen_phi_m20_m16[iSample].Fill(ptRes_sta_glb_gen)
            if ( mu.glb_gen_phi >= -1.6 and mu.glb_gen_phi <= -1.2 ): h_ptRes_sta_glb_gen_phi_m16_m12[iSample].Fill(ptRes_sta_glb_gen)
            if ( mu.glb_gen_phi >= -1.2 and mu.glb_gen_phi <= -0.8 ): h_ptRes_sta_glb_gen_phi_m12_m08[iSample].Fill(ptRes_sta_glb_gen)
            if ( mu.glb_gen_phi >= -0.8 and mu.glb_gen_phi <= -0.4 ): h_ptRes_sta_glb_gen_phi_m08_m04[iSample].Fill(ptRes_sta_glb_gen)
            if ( mu.glb_gen_phi >= -0.4 and mu.glb_gen_phi <=  0.0 ): h_ptRes_sta_glb_gen_phi_m04_m00[iSample].Fill(ptRes_sta_glb_gen)
            if ( mu.glb_gen_phi >=  0.0 and mu.glb_gen_phi <=  0.4 ): h_ptRes_sta_glb_gen_phi_p00_p04[iSample].Fill(ptRes_sta_glb_gen)
            if ( mu.glb_gen_phi >=  0.4 and mu.glb_gen_phi <=  0.8 ): h_ptRes_sta_glb_gen_phi_p04_p08[iSample].Fill(ptRes_sta_glb_gen)
            if ( mu.glb_gen_phi >=  0.8 and mu.glb_gen_phi <=  1.2 ): h_ptRes_sta_glb_gen_phi_p08_p12[iSample].Fill(ptRes_sta_glb_gen)
            if ( mu.glb_gen_phi >=  1.2 and mu.glb_gen_phi <=  1.6 ): h_ptRes_sta_glb_gen_phi_p12_p16[iSample].Fill(ptRes_sta_glb_gen)
            if ( mu.glb_gen_phi >=  1.6 and mu.glb_gen_phi <=  2.0 ): h_ptRes_sta_glb_gen_phi_p16_p20[iSample].Fill(ptRes_sta_glb_gen)
            if ( mu.glb_gen_phi >=  2.0 and mu.glb_gen_phi <=  2.4 ): h_ptRes_sta_glb_gen_phi_p20_p24[iSample].Fill(ptRes_sta_glb_gen)
            if ( mu.glb_gen_phi >=  2.4 and mu.glb_gen_phi <=  2.8 ): h_ptRes_sta_glb_gen_phi_p24_p28[iSample].Fill(ptRes_sta_glb_gen)
            if ( mu.glb_gen_phi >=  2.8 and mu.glb_gen_phi <=  3.2 ): h_ptRes_sta_glb_gen_phi_p28_p32[iSample].Fill(ptRes_sta_glb_gen)
            if ( mu.glb_gen_eta >=  -0.9 and mu.glb_gen_eta <=  0.9 ): 
              if ( mu.glb_gen_phi >= -3.2 and mu.glb_gen_phi <= -2.8 ): h_ptRes_sta_glb_genB_phi_m32_m28[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >= -2.8 and mu.glb_gen_phi <= -2.4 ): h_ptRes_sta_glb_genB_phi_m28_m24[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >= -2.4 and mu.glb_gen_phi <= -2.0 ): h_ptRes_sta_glb_genB_phi_m24_m20[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >= -2.0 and mu.glb_gen_phi <= -1.6 ): h_ptRes_sta_glb_genB_phi_m20_m16[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >= -1.6 and mu.glb_gen_phi <= -1.2 ): h_ptRes_sta_glb_genB_phi_m16_m12[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >= -1.2 and mu.glb_gen_phi <= -0.8 ): h_ptRes_sta_glb_genB_phi_m12_m08[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >= -0.8 and mu.glb_gen_phi <= -0.4 ): h_ptRes_sta_glb_genB_phi_m08_m04[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >= -0.4 and mu.glb_gen_phi <=  0.0 ): h_ptRes_sta_glb_genB_phi_m04_m00[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >=  0.0 and mu.glb_gen_phi <=  0.4 ): h_ptRes_sta_glb_genB_phi_p00_p04[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >=  0.4 and mu.glb_gen_phi <=  0.8 ): h_ptRes_sta_glb_genB_phi_p04_p08[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >=  0.8 and mu.glb_gen_phi <=  1.2 ): h_ptRes_sta_glb_genB_phi_p08_p12[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >=  1.2 and mu.glb_gen_phi <=  1.6 ): h_ptRes_sta_glb_genB_phi_p12_p16[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >=  1.6 and mu.glb_gen_phi <=  2.0 ): h_ptRes_sta_glb_genB_phi_p16_p20[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >=  2.0 and mu.glb_gen_phi <=  2.4 ): h_ptRes_sta_glb_genB_phi_p20_p24[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >=  2.4 and mu.glb_gen_phi <=  2.8 ): h_ptRes_sta_glb_genB_phi_p24_p28[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >=  2.8 and mu.glb_gen_phi <=  3.2 ): h_ptRes_sta_glb_genB_phi_p28_p32[iSample].Fill(ptRes_sta_glb_gen)
            if ( mu.glb_gen_eta >=  0.9 and mu.glb_gen_eta <=  2.4 ): 
              if ( mu.glb_gen_phi >= -3.2 and mu.glb_gen_phi <= -2.8 ): h_ptRes_sta_glb_genEOp_phi_m32_m28[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >= -2.8 and mu.glb_gen_phi <= -2.4 ): h_ptRes_sta_glb_genEOp_phi_m28_m24[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >= -2.4 and mu.glb_gen_phi <= -2.0 ): h_ptRes_sta_glb_genEOp_phi_m24_m20[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >= -2.0 and mu.glb_gen_phi <= -1.6 ): h_ptRes_sta_glb_genEOp_phi_m20_m16[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >= -1.6 and mu.glb_gen_phi <= -1.2 ): h_ptRes_sta_glb_genEOp_phi_m16_m12[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >= -1.2 and mu.glb_gen_phi <= -0.8 ): h_ptRes_sta_glb_genEOp_phi_m12_m08[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >= -0.8 and mu.glb_gen_phi <= -0.4 ): h_ptRes_sta_glb_genEOp_phi_m08_m04[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >= -0.4 and mu.glb_gen_phi <=  0.0 ): h_ptRes_sta_glb_genEOp_phi_m04_m00[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >=  0.0 and mu.glb_gen_phi <=  0.4 ): h_ptRes_sta_glb_genEOp_phi_p00_p04[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >=  0.4 and mu.glb_gen_phi <=  0.8 ): h_ptRes_sta_glb_genEOp_phi_p04_p08[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >=  0.8 and mu.glb_gen_phi <=  1.2 ): h_ptRes_sta_glb_genEOp_phi_p08_p12[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >=  1.2 and mu.glb_gen_phi <=  1.6 ): h_ptRes_sta_glb_genEOp_phi_p12_p16[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >=  1.6 and mu.glb_gen_phi <=  2.0 ): h_ptRes_sta_glb_genEOp_phi_p16_p20[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >=  2.0 and mu.glb_gen_phi <=  2.4 ): h_ptRes_sta_glb_genEOp_phi_p20_p24[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >=  2.4 and mu.glb_gen_phi <=  2.8 ): h_ptRes_sta_glb_genEOp_phi_p24_p28[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >=  2.8 and mu.glb_gen_phi <=  3.2 ): h_ptRes_sta_glb_genEOp_phi_p28_p32[iSample].Fill(ptRes_sta_glb_gen)
            if ( mu.glb_gen_eta >=  -2.4 and mu.glb_gen_eta <=  -0.9 ): 
              if ( mu.glb_gen_phi >= -3.2 and mu.glb_gen_phi <= -2.8 ): h_ptRes_sta_glb_genEOm_phi_m32_m28[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >= -2.8 and mu.glb_gen_phi <= -2.4 ): h_ptRes_sta_glb_genEOm_phi_m28_m24[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >= -2.4 and mu.glb_gen_phi <= -2.0 ): h_ptRes_sta_glb_genEOm_phi_m24_m20[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >= -2.0 and mu.glb_gen_phi <= -1.6 ): h_ptRes_sta_glb_genEOm_phi_m20_m16[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >= -1.6 and mu.glb_gen_phi <= -1.2 ): h_ptRes_sta_glb_genEOm_phi_m16_m12[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >= -1.2 and mu.glb_gen_phi <= -0.8 ): h_ptRes_sta_glb_genEOm_phi_m12_m08[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >= -0.8 and mu.glb_gen_phi <= -0.4 ): h_ptRes_sta_glb_genEOm_phi_m08_m04[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >= -0.4 and mu.glb_gen_phi <=  0.0 ): h_ptRes_sta_glb_genEOm_phi_m04_m00[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >=  0.0 and mu.glb_gen_phi <=  0.4 ): h_ptRes_sta_glb_genEOm_phi_p00_p04[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >=  0.4 and mu.glb_gen_phi <=  0.8 ): h_ptRes_sta_glb_genEOm_phi_p04_p08[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >=  0.8 and mu.glb_gen_phi <=  1.2 ): h_ptRes_sta_glb_genEOm_phi_p08_p12[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >=  1.2 and mu.glb_gen_phi <=  1.6 ): h_ptRes_sta_glb_genEOm_phi_p12_p16[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >=  1.6 and mu.glb_gen_phi <=  2.0 ): h_ptRes_sta_glb_genEOm_phi_p16_p20[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >=  2.0 and mu.glb_gen_phi <=  2.4 ): h_ptRes_sta_glb_genEOm_phi_p20_p24[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >=  2.4 and mu.glb_gen_phi <=  2.8 ): h_ptRes_sta_glb_genEOm_phi_p24_p28[iSample].Fill(ptRes_sta_glb_gen)
              if ( mu.glb_gen_phi >=  2.8 and mu.glb_gen_phi <=  3.2 ): h_ptRes_sta_glb_genEOm_phi_p28_p32[iSample].Fill(ptRes_sta_glb_gen)
        '''

        if ( mu.glb_pic and mu.glb_trk_pt > 30):
          if ( mu.glb_pic_pt != 0.0 and mu.glb_trk_pt != 0.0 ):
            ptRes_pic_trk = mu.q/mu.glb_pic_pt - mu.q/mu.glb_trk_pt
            h_ptRes_pic_trk[iSample].Fill(ptRes_pic_trk)
            # resolution vs eta
            if ( mu.glb_trk_eta >= -2.4 and mu.glb_trk_eta <= -2.1 ): h_ptRes_pic_trk_eta_m24_m21[iSample].Fill(ptRes_pic_trk)
            if ( mu.glb_trk_eta >= -2.1 and mu.glb_trk_eta <= -1.8 ): h_ptRes_pic_trk_eta_m21_m18[iSample].Fill(ptRes_pic_trk)
            if ( mu.glb_trk_eta >= -1.8 and mu.glb_trk_eta <= -1.5 ): h_ptRes_pic_trk_eta_m18_m15[iSample].Fill(ptRes_pic_trk)
            if ( mu.glb_trk_eta >= -1.5 and mu.glb_trk_eta <= -1.2 ): h_ptRes_pic_trk_eta_m15_m12[iSample].Fill(ptRes_pic_trk)
            if ( mu.glb_trk_eta >= -1.2 and mu.glb_trk_eta <= -0.9 ): h_ptRes_pic_trk_eta_m12_m09[iSample].Fill(ptRes_pic_trk)
            if ( mu.glb_trk_eta >= -0.9 and mu.glb_trk_eta <= -0.6 ): h_ptRes_pic_trk_eta_m09_m06[iSample].Fill(ptRes_pic_trk)
            if ( mu.glb_trk_eta >= -0.6 and mu.glb_trk_eta <= -0.3 ): h_ptRes_pic_trk_eta_m06_m03[iSample].Fill(ptRes_pic_trk)
            if ( mu.glb_trk_eta >= -0.3 and mu.glb_trk_eta <=  0.0 ): h_ptRes_pic_trk_eta_m03_m00[iSample].Fill(ptRes_pic_trk)
            if ( mu.glb_trk_eta >=  0.0 and mu.glb_trk_eta <=  0.3 ): h_ptRes_pic_trk_eta_p00_p03[iSample].Fill(ptRes_pic_trk)
            if ( mu.glb_trk_eta >=  0.3 and mu.glb_trk_eta <=  0.6 ): h_ptRes_pic_trk_eta_p03_p06[iSample].Fill(ptRes_pic_trk)
            if ( mu.glb_trk_eta >=  0.6 and mu.glb_trk_eta <=  0.9 ): h_ptRes_pic_trk_eta_p06_p09[iSample].Fill(ptRes_pic_trk)
            if ( mu.glb_trk_eta >=  0.9 and mu.glb_trk_eta <=  1.2 ): h_ptRes_pic_trk_eta_p09_p12[iSample].Fill(ptRes_pic_trk)
            if ( mu.glb_trk_eta >=  1.2 and mu.glb_trk_eta <=  1.5 ): h_ptRes_pic_trk_eta_p12_p15[iSample].Fill(ptRes_pic_trk)
            if ( mu.glb_trk_eta >=  1.5 and mu.glb_trk_eta <=  1.8 ): h_ptRes_pic_trk_eta_p15_p18[iSample].Fill(ptRes_pic_trk)
            if ( mu.glb_trk_eta >=  1.8 and mu.glb_trk_eta <=  2.1 ): h_ptRes_pic_trk_eta_p18_p21[iSample].Fill(ptRes_pic_trk)
            if ( mu.glb_trk_eta >=  2.1 and mu.glb_trk_eta <=  2.4 ): h_ptRes_pic_trk_eta_p21_p24[iSample].Fill(ptRes_pic_trk)
            # resolution vs phi
            if ( mu.glb_trk_phi >= -3.2 and mu.glb_trk_phi <= -2.8 ): h_ptRes_pic_trk_phi_m32_m28[iSample].Fill(ptRes_pic_trk)
            if ( mu.glb_trk_phi >= -2.8 and mu.glb_trk_phi <= -2.4 ): h_ptRes_pic_trk_phi_m28_m24[iSample].Fill(ptRes_pic_trk)
            if ( mu.glb_trk_phi >= -2.4 and mu.glb_trk_phi <= -2.0 ): h_ptRes_pic_trk_phi_m24_m20[iSample].Fill(ptRes_pic_trk)
            if ( mu.glb_trk_phi >= -2.0 and mu.glb_trk_phi <= -1.6 ): h_ptRes_pic_trk_phi_m20_m16[iSample].Fill(ptRes_pic_trk)
            if ( mu.glb_trk_phi >= -1.6 and mu.glb_trk_phi <= -1.2 ): h_ptRes_pic_trk_phi_m16_m12[iSample].Fill(ptRes_pic_trk)
            if ( mu.glb_trk_phi >= -1.2 and mu.glb_trk_phi <= -0.8 ): h_ptRes_pic_trk_phi_m12_m08[iSample].Fill(ptRes_pic_trk)
            if ( mu.glb_trk_phi >= -0.8 and mu.glb_trk_phi <= -0.4 ): h_ptRes_pic_trk_phi_m08_m04[iSample].Fill(ptRes_pic_trk)
            if ( mu.glb_trk_phi >= -0.4 and mu.glb_trk_phi <=  0.0 ): h_ptRes_pic_trk_phi_m04_m00[iSample].Fill(ptRes_pic_trk)
            if ( mu.glb_trk_phi >=  0.0 and mu.glb_trk_phi <=  0.4 ): h_ptRes_pic_trk_phi_p00_p04[iSample].Fill(ptRes_pic_trk)
            if ( mu.glb_trk_phi >=  0.4 and mu.glb_trk_phi <=  0.8 ): h_ptRes_pic_trk_phi_p04_p08[iSample].Fill(ptRes_pic_trk)
            if ( mu.glb_trk_phi >=  0.8 and mu.glb_trk_phi <=  1.2 ): h_ptRes_pic_trk_phi_p08_p12[iSample].Fill(ptRes_pic_trk)
            if ( mu.glb_trk_phi >=  1.2 and mu.glb_trk_phi <=  1.6 ): h_ptRes_pic_trk_phi_p12_p16[iSample].Fill(ptRes_pic_trk)
            if ( mu.glb_trk_phi >=  1.6 and mu.glb_trk_phi <=  2.0 ): h_ptRes_pic_trk_phi_p16_p20[iSample].Fill(ptRes_pic_trk)
            if ( mu.glb_trk_phi >=  2.0 and mu.glb_trk_phi <=  2.4 ): h_ptRes_pic_trk_phi_p20_p24[iSample].Fill(ptRes_pic_trk)
            if ( mu.glb_trk_phi >=  2.4 and mu.glb_trk_phi <=  2.8 ): h_ptRes_pic_trk_phi_p24_p28[iSample].Fill(ptRes_pic_trk)
            if ( mu.glb_trk_phi >=  2.8 and mu.glb_trk_phi <=  3.2 ): h_ptRes_pic_trk_phi_p28_p32[iSample].Fill(ptRes_pic_trk)
            
            if ( mu.glb_trk_eta >=  -0.9 and mu.glb_trk_eta <=  0.9 ): 
              if ( mu.glb_trk_phi >= -3.2 and mu.glb_trk_phi <= -2.8 ): h_ptRes_pic_trkB_phi_m32_m28[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >= -2.8 and mu.glb_trk_phi <= -2.4 ): h_ptRes_pic_trkB_phi_m28_m24[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >= -2.4 and mu.glb_trk_phi <= -2.0 ): h_ptRes_pic_trkB_phi_m24_m20[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >= -2.0 and mu.glb_trk_phi <= -1.6 ): h_ptRes_pic_trkB_phi_m20_m16[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >= -1.6 and mu.glb_trk_phi <= -1.2 ): h_ptRes_pic_trkB_phi_m16_m12[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >= -1.2 and mu.glb_trk_phi <= -0.8 ): h_ptRes_pic_trkB_phi_m12_m08[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >= -0.8 and mu.glb_trk_phi <= -0.4 ): h_ptRes_pic_trkB_phi_m08_m04[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >= -0.4 and mu.glb_trk_phi <=  0.0 ): h_ptRes_pic_trkB_phi_m04_m00[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >=  0.0 and mu.glb_trk_phi <=  0.4 ): h_ptRes_pic_trkB_phi_p00_p04[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >=  0.4 and mu.glb_trk_phi <=  0.8 ): h_ptRes_pic_trkB_phi_p04_p08[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >=  0.8 and mu.glb_trk_phi <=  1.2 ): h_ptRes_pic_trkB_phi_p08_p12[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >=  1.2 and mu.glb_trk_phi <=  1.6 ): h_ptRes_pic_trkB_phi_p12_p16[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >=  1.6 and mu.glb_trk_phi <=  2.0 ): h_ptRes_pic_trkB_phi_p16_p20[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >=  2.0 and mu.glb_trk_phi <=  2.4 ): h_ptRes_pic_trkB_phi_p20_p24[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >=  2.4 and mu.glb_trk_phi <=  2.8 ): h_ptRes_pic_trkB_phi_p24_p28[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >=  2.8 and mu.glb_trk_phi <=  3.2 ): h_ptRes_pic_trkB_phi_p28_p32[iSample].Fill(ptRes_pic_trk)
            if ( mu.glb_trk_eta >=  0.9 and mu.glb_trk_eta <=  2.4 ): 
              if ( mu.glb_trk_phi >= -3.2 and mu.glb_trk_phi <= -2.8 ): h_ptRes_pic_trkEOp_phi_m32_m28[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >= -2.8 and mu.glb_trk_phi <= -2.4 ): h_ptRes_pic_trkEOp_phi_m28_m24[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >= -2.4 and mu.glb_trk_phi <= -2.0 ): h_ptRes_pic_trkEOp_phi_m24_m20[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >= -2.0 and mu.glb_trk_phi <= -1.6 ): h_ptRes_pic_trkEOp_phi_m20_m16[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >= -1.6 and mu.glb_trk_phi <= -1.2 ): h_ptRes_pic_trkEOp_phi_m16_m12[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >= -1.2 and mu.glb_trk_phi <= -0.8 ): h_ptRes_pic_trkEOp_phi_m12_m08[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >= -0.8 and mu.glb_trk_phi <= -0.4 ): h_ptRes_pic_trkEOp_phi_m08_m04[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >= -0.4 and mu.glb_trk_phi <=  0.0 ): h_ptRes_pic_trkEOp_phi_m04_m00[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >=  0.0 and mu.glb_trk_phi <=  0.4 ): h_ptRes_pic_trkEOp_phi_p00_p04[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >=  0.4 and mu.glb_trk_phi <=  0.8 ): h_ptRes_pic_trkEOp_phi_p04_p08[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >=  0.8 and mu.glb_trk_phi <=  1.2 ): h_ptRes_pic_trkEOp_phi_p08_p12[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >=  1.2 and mu.glb_trk_phi <=  1.6 ): h_ptRes_pic_trkEOp_phi_p12_p16[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >=  1.6 and mu.glb_trk_phi <=  2.0 ): h_ptRes_pic_trkEOp_phi_p16_p20[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >=  2.0 and mu.glb_trk_phi <=  2.4 ): h_ptRes_pic_trkEOp_phi_p20_p24[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >=  2.4 and mu.glb_trk_phi <=  2.8 ): h_ptRes_pic_trkEOp_phi_p24_p28[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >=  2.8 and mu.glb_trk_phi <=  3.2 ): h_ptRes_pic_trkEOp_phi_p28_p32[iSample].Fill(ptRes_pic_trk)
            if ( mu.glb_trk_eta >=  -2.4 and mu.glb_trk_eta <=  -0.9 ): 
              if ( mu.glb_trk_phi >= -3.2 and mu.glb_trk_phi <= -2.8 ): h_ptRes_pic_trkEOm_phi_m32_m28[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >= -2.8 and mu.glb_trk_phi <= -2.4 ): h_ptRes_pic_trkEOm_phi_m28_m24[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >= -2.4 and mu.glb_trk_phi <= -2.0 ): h_ptRes_pic_trkEOm_phi_m24_m20[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >= -2.0 and mu.glb_trk_phi <= -1.6 ): h_ptRes_pic_trkEOm_phi_m20_m16[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >= -1.6 and mu.glb_trk_phi <= -1.2 ): h_ptRes_pic_trkEOm_phi_m16_m12[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >= -1.2 and mu.glb_trk_phi <= -0.8 ): h_ptRes_pic_trkEOm_phi_m12_m08[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >= -0.8 and mu.glb_trk_phi <= -0.4 ): h_ptRes_pic_trkEOm_phi_m08_m04[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >= -0.4 and mu.glb_trk_phi <=  0.0 ): h_ptRes_pic_trkEOm_phi_m04_m00[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >=  0.0 and mu.glb_trk_phi <=  0.4 ): h_ptRes_pic_trkEOm_phi_p00_p04[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >=  0.4 and mu.glb_trk_phi <=  0.8 ): h_ptRes_pic_trkEOm_phi_p04_p08[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >=  0.8 and mu.glb_trk_phi <=  1.2 ): h_ptRes_pic_trkEOm_phi_p08_p12[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >=  1.2 and mu.glb_trk_phi <=  1.6 ): h_ptRes_pic_trkEOm_phi_p12_p16[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >=  1.6 and mu.glb_trk_phi <=  2.0 ): h_ptRes_pic_trkEOm_phi_p16_p20[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >=  2.0 and mu.glb_trk_phi <=  2.4 ): h_ptRes_pic_trkEOm_phi_p20_p24[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >=  2.4 and mu.glb_trk_phi <=  2.8 ): h_ptRes_pic_trkEOm_phi_p24_p28[iSample].Fill(ptRes_pic_trk)
              if ( mu.glb_trk_phi >=  2.8 and mu.glb_trk_phi <=  3.2 ): h_ptRes_pic_trkEOm_phi_p28_p32[iSample].Fill(ptRes_pic_trk)
        '''
        if ( mu.glb_pic and mu.glb_gen_pt > 30):
          if ( mu.glb_pic_pt != 0.0 and mu.glb_gen_pt != 0.0 ):
            ptRes_pic_gen = mu.q/mu.glb_pic_pt - mu.q/mu.glb_gen_pt
            h_ptRes_pic_gen[iSample].Fill(ptRes_pic_gen)
            # resolution vs eta
            if ( mu.glb_gen_eta >= -2.4 and mu.glb_gen_eta <= -2.1 ): h_ptRes_pic_gen_eta_m24_m21[iSample].Fill(ptRes_pic_gen)
            if ( mu.glb_gen_eta >= -2.1 and mu.glb_gen_eta <= -1.8 ): h_ptRes_pic_gen_eta_m21_m18[iSample].Fill(ptRes_pic_gen)
            if ( mu.glb_gen_eta >= -1.8 and mu.glb_gen_eta <= -1.5 ): h_ptRes_pic_gen_eta_m18_m15[iSample].Fill(ptRes_pic_gen)
            if ( mu.glb_gen_eta >= -1.5 and mu.glb_gen_eta <= -1.2 ): h_ptRes_pic_gen_eta_m15_m12[iSample].Fill(ptRes_pic_gen)
            if ( mu.glb_gen_eta >= -1.2 and mu.glb_gen_eta <= -0.9 ): h_ptRes_pic_gen_eta_m12_m09[iSample].Fill(ptRes_pic_gen)
            if ( mu.glb_gen_eta >= -0.9 and mu.glb_gen_eta <= -0.6 ): h_ptRes_pic_gen_eta_m09_m06[iSample].Fill(ptRes_pic_gen)
            if ( mu.glb_gen_eta >= -0.6 and mu.glb_gen_eta <= -0.3 ): h_ptRes_pic_gen_eta_m06_m03[iSample].Fill(ptRes_pic_gen)
            if ( mu.glb_gen_eta >= -0.3 and mu.glb_gen_eta <=  0.0 ): h_ptRes_pic_gen_eta_m03_m00[iSample].Fill(ptRes_pic_gen)
            if ( mu.glb_gen_eta >=  0.0 and mu.glb_gen_eta <=  0.3 ): h_ptRes_pic_gen_eta_p00_p03[iSample].Fill(ptRes_pic_gen)
            if ( mu.glb_gen_eta >=  0.3 and mu.glb_gen_eta <=  0.6 ): h_ptRes_pic_gen_eta_p03_p06[iSample].Fill(ptRes_pic_gen)
            if ( mu.glb_gen_eta >=  0.6 and mu.glb_gen_eta <=  0.9 ): h_ptRes_pic_gen_eta_p06_p09[iSample].Fill(ptRes_pic_gen)
            if ( mu.glb_gen_eta >=  0.9 and mu.glb_gen_eta <=  1.2 ): h_ptRes_pic_gen_eta_p09_p12[iSample].Fill(ptRes_pic_gen)
            if ( mu.glb_gen_eta >=  1.2 and mu.glb_gen_eta <=  1.5 ): h_ptRes_pic_gen_eta_p12_p15[iSample].Fill(ptRes_pic_gen)
            if ( mu.glb_gen_eta >=  1.5 and mu.glb_gen_eta <=  1.8 ): h_ptRes_pic_gen_eta_p15_p18[iSample].Fill(ptRes_pic_gen)
            if ( mu.glb_gen_eta >=  1.8 and mu.glb_gen_eta <=  2.1 ): h_ptRes_pic_gen_eta_p18_p21[iSample].Fill(ptRes_pic_gen)
            if ( mu.glb_gen_eta >=  2.1 and mu.glb_gen_eta <=  2.4 ): h_ptRes_pic_gen_eta_p21_p24[iSample].Fill(ptRes_pic_gen)
            # resolution vs phi
            if ( mu.glb_gen_phi >= -3.2 and mu.glb_gen_phi <= -2.8 ): h_ptRes_pic_gen_phi_m32_m28[iSample].Fill(ptRes_pic_gen)
            if ( mu.glb_gen_phi >= -2.8 and mu.glb_gen_phi <= -2.4 ): h_ptRes_pic_gen_phi_m28_m24[iSample].Fill(ptRes_pic_gen)
            if ( mu.glb_gen_phi >= -2.4 and mu.glb_gen_phi <= -2.0 ): h_ptRes_pic_gen_phi_m24_m20[iSample].Fill(ptRes_pic_gen)
            if ( mu.glb_gen_phi >= -2.0 and mu.glb_gen_phi <= -1.6 ): h_ptRes_pic_gen_phi_m20_m16[iSample].Fill(ptRes_pic_gen)
            if ( mu.glb_gen_phi >= -1.6 and mu.glb_gen_phi <= -1.2 ): h_ptRes_pic_gen_phi_m16_m12[iSample].Fill(ptRes_pic_gen)
            if ( mu.glb_gen_phi >= -1.2 and mu.glb_gen_phi <= -0.8 ): h_ptRes_pic_gen_phi_m12_m08[iSample].Fill(ptRes_pic_gen)
            if ( mu.glb_gen_phi >= -0.8 and mu.glb_gen_phi <= -0.4 ): h_ptRes_pic_gen_phi_m08_m04[iSample].Fill(ptRes_pic_gen)
            if ( mu.glb_gen_phi >= -0.4 and mu.glb_gen_phi <=  0.0 ): h_ptRes_pic_gen_phi_m04_m00[iSample].Fill(ptRes_pic_gen)
            if ( mu.glb_gen_phi >=  0.0 and mu.glb_gen_phi <=  0.4 ): h_ptRes_pic_gen_phi_p00_p04[iSample].Fill(ptRes_pic_gen)
            if ( mu.glb_gen_phi >=  0.4 and mu.glb_gen_phi <=  0.8 ): h_ptRes_pic_gen_phi_p04_p08[iSample].Fill(ptRes_pic_gen)
            if ( mu.glb_gen_phi >=  0.8 and mu.glb_gen_phi <=  1.2 ): h_ptRes_pic_gen_phi_p08_p12[iSample].Fill(ptRes_pic_gen)
            if ( mu.glb_gen_phi >=  1.2 and mu.glb_gen_phi <=  1.6 ): h_ptRes_pic_gen_phi_p12_p16[iSample].Fill(ptRes_pic_gen)
            if ( mu.glb_gen_phi >=  1.6 and mu.glb_gen_phi <=  2.0 ): h_ptRes_pic_gen_phi_p16_p20[iSample].Fill(ptRes_pic_gen)
            if ( mu.glb_gen_phi >=  2.0 and mu.glb_gen_phi <=  2.4 ): h_ptRes_pic_gen_phi_p20_p24[iSample].Fill(ptRes_pic_gen)
            if ( mu.glb_gen_phi >=  2.4 and mu.glb_gen_phi <=  2.8 ): h_ptRes_pic_gen_phi_p24_p28[iSample].Fill(ptRes_pic_gen)
            if ( mu.glb_gen_phi >=  2.8 and mu.glb_gen_phi <=  3.2 ): h_ptRes_pic_gen_phi_p28_p32[iSample].Fill(ptRes_pic_gen)
            
            if ( mu.glb_gen_eta >=  -0.9 and mu.glb_gen_eta <=  0.9 ): 
              if ( mu.glb_gen_phi >= -3.2 and mu.glb_gen_phi <= -2.8 ): h_ptRes_pic_genB_phi_m32_m28[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >= -2.8 and mu.glb_gen_phi <= -2.4 ): h_ptRes_pic_genB_phi_m28_m24[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >= -2.4 and mu.glb_gen_phi <= -2.0 ): h_ptRes_pic_genB_phi_m24_m20[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >= -2.0 and mu.glb_gen_phi <= -1.6 ): h_ptRes_pic_genB_phi_m20_m16[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >= -1.6 and mu.glb_gen_phi <= -1.2 ): h_ptRes_pic_genB_phi_m16_m12[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >= -1.2 and mu.glb_gen_phi <= -0.8 ): h_ptRes_pic_genB_phi_m12_m08[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >= -0.8 and mu.glb_gen_phi <= -0.4 ): h_ptRes_pic_genB_phi_m08_m04[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >= -0.4 and mu.glb_gen_phi <=  0.0 ): h_ptRes_pic_genB_phi_m04_m00[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >=  0.0 and mu.glb_gen_phi <=  0.4 ): h_ptRes_pic_genB_phi_p00_p04[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >=  0.4 and mu.glb_gen_phi <=  0.8 ): h_ptRes_pic_genB_phi_p04_p08[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >=  0.8 and mu.glb_gen_phi <=  1.2 ): h_ptRes_pic_genB_phi_p08_p12[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >=  1.2 and mu.glb_gen_phi <=  1.6 ): h_ptRes_pic_genB_phi_p12_p16[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >=  1.6 and mu.glb_gen_phi <=  2.0 ): h_ptRes_pic_genB_phi_p16_p20[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >=  2.0 and mu.glb_gen_phi <=  2.4 ): h_ptRes_pic_genB_phi_p20_p24[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >=  2.4 and mu.glb_gen_phi <=  2.8 ): h_ptRes_pic_genB_phi_p24_p28[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >=  2.8 and mu.glb_gen_phi <=  3.2 ): h_ptRes_pic_genB_phi_p28_p32[iSample].Fill(ptRes_pic_gen)
            if ( mu.glb_gen_eta >=  0.9 and mu.glb_gen_eta <=  2.4 ): 
              if ( mu.glb_gen_phi >= -3.2 and mu.glb_gen_phi <= -2.8 ): h_ptRes_pic_genEOp_phi_m32_m28[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >= -2.8 and mu.glb_gen_phi <= -2.4 ): h_ptRes_pic_genEOp_phi_m28_m24[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >= -2.4 and mu.glb_gen_phi <= -2.0 ): h_ptRes_pic_genEOp_phi_m24_m20[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >= -2.0 and mu.glb_gen_phi <= -1.6 ): h_ptRes_pic_genEOp_phi_m20_m16[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >= -1.6 and mu.glb_gen_phi <= -1.2 ): h_ptRes_pic_genEOp_phi_m16_m12[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >= -1.2 and mu.glb_gen_phi <= -0.8 ): h_ptRes_pic_genEOp_phi_m12_m08[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >= -0.8 and mu.glb_gen_phi <= -0.4 ): h_ptRes_pic_genEOp_phi_m08_m04[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >= -0.4 and mu.glb_gen_phi <=  0.0 ): h_ptRes_pic_genEOp_phi_m04_m00[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >=  0.0 and mu.glb_gen_phi <=  0.4 ): h_ptRes_pic_genEOp_phi_p00_p04[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >=  0.4 and mu.glb_gen_phi <=  0.8 ): h_ptRes_pic_genEOp_phi_p04_p08[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >=  0.8 and mu.glb_gen_phi <=  1.2 ): h_ptRes_pic_genEOp_phi_p08_p12[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >=  1.2 and mu.glb_gen_phi <=  1.6 ): h_ptRes_pic_genEOp_phi_p12_p16[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >=  1.6 and mu.glb_gen_phi <=  2.0 ): h_ptRes_pic_genEOp_phi_p16_p20[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >=  2.0 and mu.glb_gen_phi <=  2.4 ): h_ptRes_pic_genEOp_phi_p20_p24[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >=  2.4 and mu.glb_gen_phi <=  2.8 ): h_ptRes_pic_genEOp_phi_p24_p28[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >=  2.8 and mu.glb_gen_phi <=  3.2 ): h_ptRes_pic_genEOp_phi_p28_p32[iSample].Fill(ptRes_pic_gen)
            if ( mu.glb_gen_eta >=  -2.4 and mu.glb_gen_eta <=  -0.9 ): 
              if ( mu.glb_gen_phi >= -3.2 and mu.glb_gen_phi <= -2.8 ): h_ptRes_pic_genEOm_phi_m32_m28[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >= -2.8 and mu.glb_gen_phi <= -2.4 ): h_ptRes_pic_genEOm_phi_m28_m24[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >= -2.4 and mu.glb_gen_phi <= -2.0 ): h_ptRes_pic_genEOm_phi_m24_m20[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >= -2.0 and mu.glb_gen_phi <= -1.6 ): h_ptRes_pic_genEOm_phi_m20_m16[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >= -1.6 and mu.glb_gen_phi <= -1.2 ): h_ptRes_pic_genEOm_phi_m16_m12[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >= -1.2 and mu.glb_gen_phi <= -0.8 ): h_ptRes_pic_genEOm_phi_m12_m08[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >= -0.8 and mu.glb_gen_phi <= -0.4 ): h_ptRes_pic_genEOm_phi_m08_m04[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >= -0.4 and mu.glb_gen_phi <=  0.0 ): h_ptRes_pic_genEOm_phi_m04_m00[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >=  0.0 and mu.glb_gen_phi <=  0.4 ): h_ptRes_pic_genEOm_phi_p00_p04[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >=  0.4 and mu.glb_gen_phi <=  0.8 ): h_ptRes_pic_genEOm_phi_p04_p08[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >=  0.8 and mu.glb_gen_phi <=  1.2 ): h_ptRes_pic_genEOm_phi_p08_p12[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >=  1.2 and mu.glb_gen_phi <=  1.6 ): h_ptRes_pic_genEOm_phi_p12_p16[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >=  1.6 and mu.glb_gen_phi <=  2.0 ): h_ptRes_pic_genEOm_phi_p16_p20[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >=  2.0 and mu.glb_gen_phi <=  2.4 ): h_ptRes_pic_genEOm_phi_p20_p24[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >=  2.4 and mu.glb_gen_phi <=  2.8 ): h_ptRes_pic_genEOm_phi_p24_p28[iSample].Fill(ptRes_pic_gen)
              if ( mu.glb_gen_phi >=  2.8 and mu.glb_gen_phi <=  3.2 ): h_ptRes_pic_genEOm_phi_p28_p32[iSample].Fill(ptRes_pic_gen)
        
        if ( mu.glb and mu.glb_trk_pt > 30):
          if ( mu.glb_gen_pt != 0.0 and mu.glb_trk_pt != 0.0 ):
            ptRes_gen_trk = mu.q/mu.glb_gen_pt - mu.q/mu.glb_trk_pt
            h_ptRes_gen_trk[iSample].Fill(ptRes_gen_trk)
            # resolution vs eta
            if ( mu.glb_trk_eta >= -2.4 and mu.glb_trk_eta <= -2.1 ): h_ptRes_gen_trk_eta_m24_m21[iSample].Fill(ptRes_gen_trk)
            if ( mu.glb_trk_eta >= -2.1 and mu.glb_trk_eta <= -1.8 ): h_ptRes_gen_trk_eta_m21_m18[iSample].Fill(ptRes_gen_trk)
            if ( mu.glb_trk_eta >= -1.8 and mu.glb_trk_eta <= -1.5 ): h_ptRes_gen_trk_eta_m18_m15[iSample].Fill(ptRes_gen_trk)
            if ( mu.glb_trk_eta >= -1.5 and mu.glb_trk_eta <= -1.2 ): h_ptRes_gen_trk_eta_m15_m12[iSample].Fill(ptRes_gen_trk)
            if ( mu.glb_trk_eta >= -1.2 and mu.glb_trk_eta <= -0.9 ): h_ptRes_gen_trk_eta_m12_m09[iSample].Fill(ptRes_gen_trk)
            if ( mu.glb_trk_eta >= -0.9 and mu.glb_trk_eta <= -0.6 ): h_ptRes_gen_trk_eta_m09_m06[iSample].Fill(ptRes_gen_trk)
            if ( mu.glb_trk_eta >= -0.6 and mu.glb_trk_eta <= -0.3 ): h_ptRes_gen_trk_eta_m06_m03[iSample].Fill(ptRes_gen_trk)
            if ( mu.glb_trk_eta >= -0.3 and mu.glb_trk_eta <=  0.0 ): h_ptRes_gen_trk_eta_m03_m00[iSample].Fill(ptRes_gen_trk)
            if ( mu.glb_trk_eta >=  0.0 and mu.glb_trk_eta <=  0.3 ): h_ptRes_gen_trk_eta_p00_p03[iSample].Fill(ptRes_gen_trk)
            if ( mu.glb_trk_eta >=  0.3 and mu.glb_trk_eta <=  0.6 ): h_ptRes_gen_trk_eta_p03_p06[iSample].Fill(ptRes_gen_trk)
            if ( mu.glb_trk_eta >=  0.6 and mu.glb_trk_eta <=  0.9 ): h_ptRes_gen_trk_eta_p06_p09[iSample].Fill(ptRes_gen_trk)
            if ( mu.glb_trk_eta >=  0.9 and mu.glb_trk_eta <=  1.2 ): h_ptRes_gen_trk_eta_p09_p12[iSample].Fill(ptRes_gen_trk)
            if ( mu.glb_trk_eta >=  1.2 and mu.glb_trk_eta <=  1.5 ): h_ptRes_gen_trk_eta_p12_p15[iSample].Fill(ptRes_gen_trk)
            if ( mu.glb_trk_eta >=  1.5 and mu.glb_trk_eta <=  1.8 ): h_ptRes_gen_trk_eta_p15_p18[iSample].Fill(ptRes_gen_trk)
            if ( mu.glb_trk_eta >=  1.8 and mu.glb_trk_eta <=  2.1 ): h_ptRes_gen_trk_eta_p18_p21[iSample].Fill(ptRes_gen_trk)
            if ( mu.glb_trk_eta >=  2.1 and mu.glb_trk_eta <=  2.4 ): h_ptRes_gen_trk_eta_p21_p24[iSample].Fill(ptRes_gen_trk)
            # resolution vs phi
            if ( mu.glb_trk_phi >= -3.2 and mu.glb_trk_phi <= -2.8 ): h_ptRes_gen_trk_phi_m32_m28[iSample].Fill(ptRes_gen_trk)
            if ( mu.glb_trk_phi >= -2.8 and mu.glb_trk_phi <= -2.4 ): h_ptRes_gen_trk_phi_m28_m24[iSample].Fill(ptRes_gen_trk)
            if ( mu.glb_trk_phi >= -2.4 and mu.glb_trk_phi <= -2.0 ): h_ptRes_gen_trk_phi_m24_m20[iSample].Fill(ptRes_gen_trk)
            if ( mu.glb_trk_phi >= -2.0 and mu.glb_trk_phi <= -1.6 ): h_ptRes_gen_trk_phi_m20_m16[iSample].Fill(ptRes_gen_trk)
            if ( mu.glb_trk_phi >= -1.6 and mu.glb_trk_phi <= -1.2 ): h_ptRes_gen_trk_phi_m16_m12[iSample].Fill(ptRes_gen_trk)
            if ( mu.glb_trk_phi >= -1.2 and mu.glb_trk_phi <= -0.8 ): h_ptRes_gen_trk_phi_m12_m08[iSample].Fill(ptRes_gen_trk)
            if ( mu.glb_trk_phi >= -0.8 and mu.glb_trk_phi <= -0.4 ): h_ptRes_gen_trk_phi_m08_m04[iSample].Fill(ptRes_gen_trk)
            if ( mu.glb_trk_phi >= -0.4 and mu.glb_trk_phi <=  0.0 ): h_ptRes_gen_trk_phi_m04_m00[iSample].Fill(ptRes_gen_trk)
            if ( mu.glb_trk_phi >=  0.0 and mu.glb_trk_phi <=  0.4 ): h_ptRes_gen_trk_phi_p00_p04[iSample].Fill(ptRes_gen_trk)
            if ( mu.glb_trk_phi >=  0.4 and mu.glb_trk_phi <=  0.8 ): h_ptRes_gen_trk_phi_p04_p08[iSample].Fill(ptRes_gen_trk)
            if ( mu.glb_trk_phi >=  0.8 and mu.glb_trk_phi <=  1.2 ): h_ptRes_gen_trk_phi_p08_p12[iSample].Fill(ptRes_gen_trk)
            if ( mu.glb_trk_phi >=  1.2 and mu.glb_trk_phi <=  1.6 ): h_ptRes_gen_trk_phi_p12_p16[iSample].Fill(ptRes_gen_trk)
            if ( mu.glb_trk_phi >=  1.6 and mu.glb_trk_phi <=  2.0 ): h_ptRes_gen_trk_phi_p16_p20[iSample].Fill(ptRes_gen_trk)
            if ( mu.glb_trk_phi >=  2.0 and mu.glb_trk_phi <=  2.4 ): h_ptRes_gen_trk_phi_p20_p24[iSample].Fill(ptRes_gen_trk)
            if ( mu.glb_trk_phi >=  2.4 and mu.glb_trk_phi <=  2.8 ): h_ptRes_gen_trk_phi_p24_p28[iSample].Fill(ptRes_gen_trk)
            if ( mu.glb_trk_phi >=  2.8 and mu.glb_trk_phi <=  3.2 ): h_ptRes_gen_trk_phi_p28_p32[iSample].Fill(ptRes_gen_trk)
            
            if ( mu.glb_trk_eta >=  -0.9 and mu.glb_trk_eta <=  0.9 ): 
              if ( mu.glb_trk_phi >= -3.2 and mu.glb_trk_phi <= -2.8 ): h_ptRes_gen_trkB_phi_m32_m28[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >= -2.8 and mu.glb_trk_phi <= -2.4 ): h_ptRes_gen_trkB_phi_m28_m24[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >= -2.4 and mu.glb_trk_phi <= -2.0 ): h_ptRes_gen_trkB_phi_m24_m20[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >= -2.0 and mu.glb_trk_phi <= -1.6 ): h_ptRes_gen_trkB_phi_m20_m16[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >= -1.6 and mu.glb_trk_phi <= -1.2 ): h_ptRes_gen_trkB_phi_m16_m12[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >= -1.2 and mu.glb_trk_phi <= -0.8 ): h_ptRes_gen_trkB_phi_m12_m08[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >= -0.8 and mu.glb_trk_phi <= -0.4 ): h_ptRes_gen_trkB_phi_m08_m04[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >= -0.4 and mu.glb_trk_phi <=  0.0 ): h_ptRes_gen_trkB_phi_m04_m00[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >=  0.0 and mu.glb_trk_phi <=  0.4 ): h_ptRes_gen_trkB_phi_p00_p04[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >=  0.4 and mu.glb_trk_phi <=  0.8 ): h_ptRes_gen_trkB_phi_p04_p08[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >=  0.8 and mu.glb_trk_phi <=  1.2 ): h_ptRes_gen_trkB_phi_p08_p12[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >=  1.2 and mu.glb_trk_phi <=  1.6 ): h_ptRes_gen_trkB_phi_p12_p16[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >=  1.6 and mu.glb_trk_phi <=  2.0 ): h_ptRes_gen_trkB_phi_p16_p20[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >=  2.0 and mu.glb_trk_phi <=  2.4 ): h_ptRes_gen_trkB_phi_p20_p24[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >=  2.4 and mu.glb_trk_phi <=  2.8 ): h_ptRes_gen_trkB_phi_p24_p28[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >=  2.8 and mu.glb_trk_phi <=  3.2 ): h_ptRes_gen_trkB_phi_p28_p32[iSample].Fill(ptRes_gen_trk)
            if ( mu.glb_trk_eta >=  0.9 and mu.glb_trk_eta <=  2.4 ): 
              if ( mu.glb_trk_phi >= -3.2 and mu.glb_trk_phi <= -2.8 ): h_ptRes_gen_trkEOp_phi_m32_m28[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >= -2.8 and mu.glb_trk_phi <= -2.4 ): h_ptRes_gen_trkEOp_phi_m28_m24[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >= -2.4 and mu.glb_trk_phi <= -2.0 ): h_ptRes_gen_trkEOp_phi_m24_m20[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >= -2.0 and mu.glb_trk_phi <= -1.6 ): h_ptRes_gen_trkEOp_phi_m20_m16[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >= -1.6 and mu.glb_trk_phi <= -1.2 ): h_ptRes_gen_trkEOp_phi_m16_m12[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >= -1.2 and mu.glb_trk_phi <= -0.8 ): h_ptRes_gen_trkEOp_phi_m12_m08[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >= -0.8 and mu.glb_trk_phi <= -0.4 ): h_ptRes_gen_trkEOp_phi_m08_m04[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >= -0.4 and mu.glb_trk_phi <=  0.0 ): h_ptRes_gen_trkEOp_phi_m04_m00[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >=  0.0 and mu.glb_trk_phi <=  0.4 ): h_ptRes_gen_trkEOp_phi_p00_p04[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >=  0.4 and mu.glb_trk_phi <=  0.8 ): h_ptRes_gen_trkEOp_phi_p04_p08[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >=  0.8 and mu.glb_trk_phi <=  1.2 ): h_ptRes_gen_trkEOp_phi_p08_p12[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >=  1.2 and mu.glb_trk_phi <=  1.6 ): h_ptRes_gen_trkEOp_phi_p12_p16[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >=  1.6 and mu.glb_trk_phi <=  2.0 ): h_ptRes_gen_trkEOp_phi_p16_p20[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >=  2.0 and mu.glb_trk_phi <=  2.4 ): h_ptRes_gen_trkEOp_phi_p20_p24[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >=  2.4 and mu.glb_trk_phi <=  2.8 ): h_ptRes_gen_trkEOp_phi_p24_p28[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >=  2.8 and mu.glb_trk_phi <=  3.2 ): h_ptRes_gen_trkEOp_phi_p28_p32[iSample].Fill(ptRes_gen_trk)
            if ( mu.glb_trk_eta >=  -2.4 and mu.glb_trk_eta <=  -0.9 ): 
              if ( mu.glb_trk_phi >= -3.2 and mu.glb_trk_phi <= -2.8 ): h_ptRes_gen_trkEOm_phi_m32_m28[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >= -2.8 and mu.glb_trk_phi <= -2.4 ): h_ptRes_gen_trkEOm_phi_m28_m24[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >= -2.4 and mu.glb_trk_phi <= -2.0 ): h_ptRes_gen_trkEOm_phi_m24_m20[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >= -2.0 and mu.glb_trk_phi <= -1.6 ): h_ptRes_gen_trkEOm_phi_m20_m16[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >= -1.6 and mu.glb_trk_phi <= -1.2 ): h_ptRes_gen_trkEOm_phi_m16_m12[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >= -1.2 and mu.glb_trk_phi <= -0.8 ): h_ptRes_gen_trkEOm_phi_m12_m08[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >= -0.8 and mu.glb_trk_phi <= -0.4 ): h_ptRes_gen_trkEOm_phi_m08_m04[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >= -0.4 and mu.glb_trk_phi <=  0.0 ): h_ptRes_gen_trkEOm_phi_m04_m00[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >=  0.0 and mu.glb_trk_phi <=  0.4 ): h_ptRes_gen_trkEOm_phi_p00_p04[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >=  0.4 and mu.glb_trk_phi <=  0.8 ): h_ptRes_gen_trkEOm_phi_p04_p08[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >=  0.8 and mu.glb_trk_phi <=  1.2 ): h_ptRes_gen_trkEOm_phi_p08_p12[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >=  1.2 and mu.glb_trk_phi <=  1.6 ): h_ptRes_gen_trkEOm_phi_p12_p16[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >=  1.6 and mu.glb_trk_phi <=  2.0 ): h_ptRes_gen_trkEOm_phi_p16_p20[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >=  2.0 and mu.glb_trk_phi <=  2.4 ): h_ptRes_gen_trkEOm_phi_p20_p24[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >=  2.4 and mu.glb_trk_phi <=  2.8 ): h_ptRes_gen_trkEOm_phi_p24_p28[iSample].Fill(ptRes_gen_trk)
              if ( mu.glb_trk_phi >=  2.8 and mu.glb_trk_phi <=  3.2 ): h_ptRes_gen_trkEOm_phi_p28_p32[iSample].Fill(ptRes_gen_trk)
    '''
        
    if ( fillRecoDimuons ):
      counterRecoDimuons = 0 # reset counter for every file
      treeName = "muAlAnalyzer/recoDimuons"
      print >> sys.stderr, "      Read tree", treeName
      recoDimuons = tfile.Get(treeName)
      print >> sys.stderr, "         Total number of entries in the tree:", recoDimuons.GetEntriesFast()
      
      for dm in recoDimuons:
        if maxEntries > 0 and counterRecoDimuons >= maxEntries:
          break
        if ( not counterRecoDimuons%100000 ):
          print >> sys.stderr, counterRecoDimuons
        counterRecoDimuons = counterRecoDimuons + 1
        if ( dm.sta and dm.glb and dm.pos_glb_pt > 30 and dm.neg_glb_pt > 30):
#          h_m_sta[iSample].Fill(dm.sta_m)
          
          # resolution vs eta
          if ( dm.pos_sta_eta >= -2.4 and dm.pos_sta_eta <= -2.1 ): h_m_sta_etaMuP_m24_m21[iSample].Fill(dm.sta_m)
          if ( dm.pos_sta_eta >= -2.1 and dm.pos_sta_eta <= -1.8 ): h_m_sta_etaMuP_m21_m18[iSample].Fill(dm.sta_m)
          if ( dm.pos_sta_eta >= -1.8 and dm.pos_sta_eta <= -1.5 ): h_m_sta_etaMuP_m18_m15[iSample].Fill(dm.sta_m)
          if ( dm.pos_sta_eta >= -1.5 and dm.pos_sta_eta <= -1.2 ): h_m_sta_etaMuP_m15_m12[iSample].Fill(dm.sta_m)
          if ( dm.pos_sta_eta >= -1.2 and dm.pos_sta_eta <= -0.9 ): h_m_sta_etaMuP_m12_m09[iSample].Fill(dm.sta_m)
          if ( dm.pos_sta_eta >= -0.9 and dm.pos_sta_eta <= -0.6 ): h_m_sta_etaMuP_m09_m06[iSample].Fill(dm.sta_m)
          if ( dm.pos_sta_eta >= -0.6 and dm.pos_sta_eta <= -0.3 ): h_m_sta_etaMuP_m06_m03[iSample].Fill(dm.sta_m)
          if ( dm.pos_sta_eta >= -0.3 and dm.pos_sta_eta <=  0.0 ): h_m_sta_etaMuP_m03_m00[iSample].Fill(dm.sta_m)
          if ( dm.pos_sta_eta >=  0.0 and dm.pos_sta_eta <=  0.3 ): h_m_sta_etaMuP_p00_p03[iSample].Fill(dm.sta_m)
          if ( dm.pos_sta_eta >=  0.3 and dm.pos_sta_eta <=  0.6 ): h_m_sta_etaMuP_p03_p06[iSample].Fill(dm.sta_m)
          if ( dm.pos_sta_eta >=  0.6 and dm.pos_sta_eta <=  0.9 ): h_m_sta_etaMuP_p06_p09[iSample].Fill(dm.sta_m)
          if ( dm.pos_sta_eta >=  0.9 and dm.pos_sta_eta <=  1.2 ): h_m_sta_etaMuP_p09_p12[iSample].Fill(dm.sta_m)
          if ( dm.pos_sta_eta >=  1.2 and dm.pos_sta_eta <=  1.5 ): h_m_sta_etaMuP_p12_p15[iSample].Fill(dm.sta_m)
          if ( dm.pos_sta_eta >=  1.5 and dm.pos_sta_eta <=  1.8 ): h_m_sta_etaMuP_p15_p18[iSample].Fill(dm.sta_m)
          if ( dm.pos_sta_eta >=  1.8 and dm.pos_sta_eta <=  2.1 ): h_m_sta_etaMuP_p18_p21[iSample].Fill(dm.sta_m)
          if ( dm.pos_sta_eta >=  2.1 and dm.pos_sta_eta <=  2.4 ): h_m_sta_etaMuP_p21_p24[iSample].Fill(dm.sta_m)
          # resolution vs phi
          if ( dm.pos_sta_phi >= -3.2 and dm.pos_sta_phi <= -2.8 ): h_m_sta_phiMuP_m32_m28[iSample].Fill(dm.sta_m)
          if ( dm.pos_sta_phi >= -2.8 and dm.pos_sta_phi <= -2.4 ): h_m_sta_phiMuP_m28_m24[iSample].Fill(dm.sta_m)
          if ( dm.pos_sta_phi >= -2.4 and dm.pos_sta_phi <= -2.0 ): h_m_sta_phiMuP_m24_m20[iSample].Fill(dm.sta_m)
          if ( dm.pos_sta_phi >= -2.0 and dm.pos_sta_phi <= -1.6 ): h_m_sta_phiMuP_m20_m16[iSample].Fill(dm.sta_m)
          if ( dm.pos_sta_phi >= -1.6 and dm.pos_sta_phi <= -1.2 ): h_m_sta_phiMuP_m16_m12[iSample].Fill(dm.sta_m)
          if ( dm.pos_sta_phi >= -1.2 and dm.pos_sta_phi <= -0.8 ): h_m_sta_phiMuP_m12_m08[iSample].Fill(dm.sta_m)
          if ( dm.pos_sta_phi >= -0.8 and dm.pos_sta_phi <= -0.4 ): h_m_sta_phiMuP_m08_m04[iSample].Fill(dm.sta_m)
          if ( dm.pos_sta_phi >= -0.4 and dm.pos_sta_phi <=  0.0 ): h_m_sta_phiMuP_m04_m00[iSample].Fill(dm.sta_m)
          if ( dm.pos_sta_phi >=  0.0 and dm.pos_sta_phi <=  0.4 ): h_m_sta_phiMuP_p00_p04[iSample].Fill(dm.sta_m)
          if ( dm.pos_sta_phi >=  0.4 and dm.pos_sta_phi <=  0.8 ): h_m_sta_phiMuP_p04_p08[iSample].Fill(dm.sta_m)
          if ( dm.pos_sta_phi >=  0.8 and dm.pos_sta_phi <=  1.2 ): h_m_sta_phiMuP_p08_p12[iSample].Fill(dm.sta_m)
          if ( dm.pos_sta_phi >=  1.2 and dm.pos_sta_phi <=  1.6 ): h_m_sta_phiMuP_p12_p16[iSample].Fill(dm.sta_m)
          if ( dm.pos_sta_phi >=  1.6 and dm.pos_sta_phi <=  2.0 ): h_m_sta_phiMuP_p16_p20[iSample].Fill(dm.sta_m)
          if ( dm.pos_sta_phi >=  2.0 and dm.pos_sta_phi <=  2.4 ): h_m_sta_phiMuP_p20_p24[iSample].Fill(dm.sta_m)
          if ( dm.pos_sta_phi >=  2.4 and dm.pos_sta_phi <=  2.8 ): h_m_sta_phiMuP_p24_p28[iSample].Fill(dm.sta_m)
          if ( dm.pos_sta_phi >=  2.8 and dm.pos_sta_phi <=  3.2 ): h_m_sta_phiMuP_p28_p32[iSample].Fill(dm.sta_m)
          
          if ( dm.pos_sta_eta >=  -0.9 and dm.pos_sta_eta <=  0.9 ): 
            if ( dm.pos_sta_phi >= -3.2 and dm.pos_sta_phi <= -2.8 ): h_m_staB_phiMuP_m32_m28[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >= -2.8 and dm.pos_sta_phi <= -2.4 ): h_m_staB_phiMuP_m28_m24[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >= -2.4 and dm.pos_sta_phi <= -2.0 ): h_m_staB_phiMuP_m24_m20[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >= -2.0 and dm.pos_sta_phi <= -1.6 ): h_m_staB_phiMuP_m20_m16[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >= -1.6 and dm.pos_sta_phi <= -1.2 ): h_m_staB_phiMuP_m16_m12[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >= -1.2 and dm.pos_sta_phi <= -0.8 ): h_m_staB_phiMuP_m12_m08[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >= -0.8 and dm.pos_sta_phi <= -0.4 ): h_m_staB_phiMuP_m08_m04[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >= -0.4 and dm.pos_sta_phi <=  0.0 ): h_m_staB_phiMuP_m04_m00[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >=  0.0 and dm.pos_sta_phi <=  0.4 ): h_m_staB_phiMuP_p00_p04[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >=  0.4 and dm.pos_sta_phi <=  0.8 ): h_m_staB_phiMuP_p04_p08[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >=  0.8 and dm.pos_sta_phi <=  1.2 ): h_m_staB_phiMuP_p08_p12[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >=  1.2 and dm.pos_sta_phi <=  1.6 ): h_m_staB_phiMuP_p12_p16[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >=  1.6 and dm.pos_sta_phi <=  2.0 ): h_m_staB_phiMuP_p16_p20[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >=  2.0 and dm.pos_sta_phi <=  2.4 ): h_m_staB_phiMuP_p20_p24[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >=  2.4 and dm.pos_sta_phi <=  2.8 ): h_m_staB_phiMuP_p24_p28[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >=  2.8 and dm.pos_sta_phi <=  3.2 ): h_m_staB_phiMuP_p28_p32[iSample].Fill(dm.sta_m)
          if ( dm.pos_sta_eta >=  0.9 and dm.pos_sta_eta <=  2.4 ): 
            if ( dm.pos_sta_phi >= -3.2 and dm.pos_sta_phi <= -2.8 ): h_m_staEOp_phiMuP_m32_m28[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >= -2.8 and dm.pos_sta_phi <= -2.4 ): h_m_staEOp_phiMuP_m28_m24[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >= -2.4 and dm.pos_sta_phi <= -2.0 ): h_m_staEOp_phiMuP_m24_m20[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >= -2.0 and dm.pos_sta_phi <= -1.6 ): h_m_staEOp_phiMuP_m20_m16[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >= -1.6 and dm.pos_sta_phi <= -1.2 ): h_m_staEOp_phiMuP_m16_m12[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >= -1.2 and dm.pos_sta_phi <= -0.8 ): h_m_staEOp_phiMuP_m12_m08[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >= -0.8 and dm.pos_sta_phi <= -0.4 ): h_m_staEOp_phiMuP_m08_m04[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >= -0.4 and dm.pos_sta_phi <=  0.0 ): h_m_staEOp_phiMuP_m04_m00[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >=  0.0 and dm.pos_sta_phi <=  0.4 ): h_m_staEOp_phiMuP_p00_p04[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >=  0.4 and dm.pos_sta_phi <=  0.8 ): h_m_staEOp_phiMuP_p04_p08[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >=  0.8 and dm.pos_sta_phi <=  1.2 ): h_m_staEOp_phiMuP_p08_p12[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >=  1.2 and dm.pos_sta_phi <=  1.6 ): h_m_staEOp_phiMuP_p12_p16[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >=  1.6 and dm.pos_sta_phi <=  2.0 ): h_m_staEOp_phiMuP_p16_p20[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >=  2.0 and dm.pos_sta_phi <=  2.4 ): h_m_staEOp_phiMuP_p20_p24[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >=  2.4 and dm.pos_sta_phi <=  2.8 ): h_m_staEOp_phiMuP_p24_p28[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >=  2.8 and dm.pos_sta_phi <=  3.2 ): h_m_staEOp_phiMuP_p28_p32[iSample].Fill(dm.sta_m)
          if ( dm.pos_sta_eta >=  -2.4 and dm.pos_sta_eta <=  -0.9 ): 
            if ( dm.pos_sta_phi >= -3.2 and dm.pos_sta_phi <= -2.8 ): h_m_staEOm_phiMuP_m32_m28[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >= -2.8 and dm.pos_sta_phi <= -2.4 ): h_m_staEOm_phiMuP_m28_m24[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >= -2.4 and dm.pos_sta_phi <= -2.0 ): h_m_staEOm_phiMuP_m24_m20[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >= -2.0 and dm.pos_sta_phi <= -1.6 ): h_m_staEOm_phiMuP_m20_m16[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >= -1.6 and dm.pos_sta_phi <= -1.2 ): h_m_staEOm_phiMuP_m16_m12[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >= -1.2 and dm.pos_sta_phi <= -0.8 ): h_m_staEOm_phiMuP_m12_m08[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >= -0.8 and dm.pos_sta_phi <= -0.4 ): h_m_staEOm_phiMuP_m08_m04[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >= -0.4 and dm.pos_sta_phi <=  0.0 ): h_m_staEOm_phiMuP_m04_m00[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >=  0.0 and dm.pos_sta_phi <=  0.4 ): h_m_staEOm_phiMuP_p00_p04[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >=  0.4 and dm.pos_sta_phi <=  0.8 ): h_m_staEOm_phiMuP_p04_p08[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >=  0.8 and dm.pos_sta_phi <=  1.2 ): h_m_staEOm_phiMuP_p08_p12[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >=  1.2 and dm.pos_sta_phi <=  1.6 ): h_m_staEOm_phiMuP_p12_p16[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >=  1.6 and dm.pos_sta_phi <=  2.0 ): h_m_staEOm_phiMuP_p16_p20[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >=  2.0 and dm.pos_sta_phi <=  2.4 ): h_m_staEOm_phiMuP_p20_p24[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >=  2.4 and dm.pos_sta_phi <=  2.8 ): h_m_staEOm_phiMuP_p24_p28[iSample].Fill(dm.sta_m)
            if ( dm.pos_sta_phi >=  2.8 and dm.pos_sta_phi <=  3.2 ): h_m_staEOm_phiMuP_p28_p32[iSample].Fill(dm.sta_m)
    
      print >> sys.stderr, "         Processed number of entries:", counterRecoMuons
      


